INSERT INTO burgers (name,devoured) VALUES ('New Bacon-ings Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('Rest in Peas Burger ',true);
INSERT INTO burgers (name,devoured) VALUES ('I Have Created a Muenster Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('Fig-eta bout it Burger',true);
INSERT INTO burgers (name,devoured) VALUES ('Thank God its Fried Egg Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('Krauted House Burger',true);
INSERT INTO burgers (name,devoured) VALUES ('Pablano Picasso Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('National Past Thyme Burger',true);
INSERT INTO burgers (name,devoured) VALUES ('Beets Me Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('Edward James Olive-most Burger',true);
INSERT INTO burgers (name,devoured) VALUES ('Let it Snow Peas Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('Shes a Super Leak Burger',true);
INSERT INTO burgers (name,devoured) VALUES ('The Grand Brie Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('I Heartichoke You Burger ',true);
INSERT INTO burgers (name,devoured) VALUES ('Shake Your Honey Maker Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('I Dont Bay Leaf in Magic Burger',true);
INSERT INTO burgers (name,devoured) VALUES ('Knife to Meat You Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('Lets Get Frisee Burger ',true);
INSERT INTO burgers (name,devoured) VALUES ('Not if I Can Kelp it Burger',false);
INSERT INTO burgers (name,devoured) VALUES ('Chorizo Your Own Advendure Burger ',true);
